#!/bin/sh
set -e

BASEDIR=$(pwd)

mkdir -p $BASEDIR/toolchain/clang
cd $BASEDIR/toolchain/clang

# build llvm and clang binaries
cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="X86;ARM" \
      -DLLVM_EXTERNAL_CLANG_SOURCE_DIR=../../external/clang \
      -DCMAKE_C_FLAGS="-O2" ../../external/llvm/
make -j $(nproc)

cd $BASEDIR

#TODO: copy include header (now in /usr/include)
# include patch for binutils
# enable optimization for llvm (more stuff?)
# test with gcc-4.8 binaries if there are errors
# document renaming of binaries of cross compiler build and export flag
# review other prebuilt tools from misc, tools, devtools and sdk
# search for bin directories in external and remove binaries
