#!/bin/sh
set -e

BASEDIR=$( dirname $0 )

mkdir -p $BASEDIR/prebuilt/common/apps/

# F-Droid
curl -L -o $BASEDIR/prebuilt/common/apps/FDroid.apk -O -L https://f-droid.org/FDroid.apk
curl -L -o $BASEDIR/prebuilt/common/apps/FDroid.apk.asc -O -L https://f-droid.org/FDroid.apk.asc
gpg --armor --verify $BASEDIR/prebuilt/common/apps/FDroid.apk.asc $BASEDIR/prebuilt/common/apps/FDroid.apk

# Terminal Emulator
curl -L -o $BASEDIR/prebuilt/common/apps/TerminalEmulator.apk -O -L https://f-droid.org/repo/jackpal.androidterm_71.apk
curl -L -o $BASEDIR/prebuilt/common/apps/TerminalEmulator.apk.asc -O -L https://f-droid.org/repo/jackpal.androidterm_71.apk.asc
gpg --armor --verify $BASEDIR/prebuilt/common/apps/TerminalEmulator.apk.asc $BASEDIR/prebuilt/common/apps/TerminalEmulator.apk
unzip -o -d $BASEDIR/prebuilt/common/apps/ $BASEDIR/prebuilt/common/apps/TerminalEmulator.apk lib/armeabi/libjackpal-termexec2.so lib/armeabi/libjackpal-androidterm5.so
