#!/bin/sh
set -e

BASEDIR=$( dirname $0 )

mkdir -p $BASEDIR/prebuilt/common/apps/

# F-Droid
curl -L -o $BASEDIR/prebuilt/common/apps/FDroid.apk -O -L https://f-droid.org/FDroid.apk
curl -L -o $BASEDIR/prebuilt/common/apps/FDroid.apk.asc -O -L https://f-droid.org/FDroid.apk.asc
gpg --armor --verify $BASEDIR/prebuilt/common/apps/FDroid.apk.asc $BASEDIR/prebuilt/common/apps/FDroid.apk
